# Generated by Django 4.2.21 on 2025-06-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='teste_temp',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='usuario',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
